### ISSUE TITLE
Execution environments

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#100]
[details](https://github.com/chkware/cli/issues/100#issuecomment-1364926561)

- [x] `execute module for testcase`
- [x] #160
- [x] #159
- [x] #166
- [x] Manage out-file request messages
- [x] #168
- [x] #170
- [x] #173

**Comment by 0hsn** [comment]
**What**

Execution environments are core to `chkware` system. An execution env refers to a space where a spec file gets executed, taking related or by passed information in the form of variable; and execution env passes resulting information after execution are successfully made.

Think of following command, 
```bash
$ chk http SomeRequestFile.chk
```
After we run this command the supposedly do: 
- create an execution env
- pass the script to the env
- pass any variables / parameters passed to it
- execute an worker (`http` or `test-spec`) and get corresponding response output
- pass it to caller environment
- caller then displays the received information. any means feasible

**How**

An executor need following information to be fed before execution
```yaml
execute:
  # name of a worker
  file: Name_Of_A_Worker.chk

  # variables / data to be passed to execution env
  with: {
    var: val,
    ...
  }

  # where to store resulting output
  result: $var 
```

**Where**

- `execute` module should handle all the code regarding execution environment, cycle, clean-up, etc
- execution env be made from any place. For current version we should support command line and `test-spec`.
