### ISSUE TITLE
Debug or logging back-end

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#212]
- Set a debug flag, with filepath support; to write log

**Comment by 0hsn** [comment]
#### Another idea

- There can be `before` and `after` block for each step
- And no global `code` block

##### Caveats

- This can help debug before and after executions; also adds flexibility to alter variables and data before and after execution
- This adds more complexity and welcomes nasty codes

eg:

```yml
name: Name of the workflow
steps:
  - name: Title of the step
    uses: fetch

    variables:
      numberOfusers: <% var_a %>
      
    before: <%
      # this block runs after the execution of this step done
      # this will display the content in pretty format when --debug enabled (default)
      debug('_steps.0._response')

      # setting a variable in local variable scope
      set var_s = length('_steps.0._response')
      %>

    after: <%
      # this block runs after the execution of this step done
      # this will display the content in pretty format when --debug enabled (default)
      debug('_steps.0._response')

      # setting a variable in local variable scope
      set var_s = length('_steps.0._response')
      %>
```
