### ISSUE TITLE
Add message variables to assert

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#219]
- `pass: ...` => user able to add a message when the assertion passes
- `fail: ...` => user able to add a message when the assertion fails

Fx:

```yml
- type: AssertEqual
  actual: "{$_response.body.name}"
  expected: "Test User Fahim"
  pass: "Test name found"
  fail: "Test name not found"
```
