### ISSUE TITLE
support for `return` part of response of `http` spec

### ISSUE THREAD

**Issue by 0hsn** [chkware/cli#91]
After a successful request / response phase an `exucutor` should be able to `return` the response to call context. 
Hence 
- `http` spec should use a variable internally to hold the response data before sent. 
- This variable is of type an immutable dictionary; consists of 4 parts: `code`, `headers`, `body` and `raw`
```yaml
response: {
  code: int,
  headers: dict,
  body: any,
  raw: object
}
```
- User should be able to specify which part of this immutable dictionary they want to export in a separate key under `request`. i.e:
```yaml
request:
  ...
  return: .body
  ...
```
